name: "Multi Event Pipeline/Workflow"

on:
  push:
    branches:
      - main
      - master

  schedule:
    - cron: "0 10 * * 4" # Every Thursday and Sunday at 10:00 UTC

  pull_request:
    branches:
      - master
    types:
      - closed

  workflow_dispatch:

jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on push"
        run: echo "Workflow triggered by push"

  on-pull-request:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request"
        run: echo "Workflow triggered by pull request"

  on-pull-request-closed:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest # ✅ fixed typo
    steps:
      - name: "Running on pull request closed"
        run: echo "Running on pull request closed"

  on-workflow-dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: "Running in workflow dispatch"
        run: echo "Running in workflow dispatch"

  on-schedule:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on schedule"
        run: echo "Workflow triggered by schedule"
