name: "Multi Event Pipeline/Workflow"

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
        - master

  workflow_dispatch:

jobs: 
  on-push: 
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on push"
        run: echo "Workflow triggered by push"

  on-pull-request: 
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request"
        run: echo "Workflow triggered by pull request"
        
  on-workflow-dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: " running in workflow dispatch"
        run: echo"runnig in workflow dispatch"