name: "Multi Event Pipeline/Workflow"

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
        - master

    types:
        [closed]
  workflow_dispatch:

jobs: 
  on-push: 
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on push"
        run: echo "Workflow triggered by push"

  on-pull-request: 
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request"
        run: echo "Workflow triggered by pull request"

  on-pull-request-closed:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ununtu-latest
    steps:
      - name: "running on pull request closed"
        run: echo "Running on pull request closed"

  on-workflow-dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: " running in workflow dispatch"
        run: echo "runnig in workflow dispatch"